# Generated by Django 4.0.3 on 2022-04-03 17:18

from django.db import migrations, models
import phy_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_alter_wordmodel_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordmodel',
            options={'verbose_name': '未定义模型名称', 'verbose_name_plural': '未定义模型名称'},
        ),
        migrations.RemoveField(
            model_name='wordmodel',
            name='modified_datetime',
        ),
        migrations.AddField(
            model_name='wordmodel',
            name='is_active',
            field=phy_django.models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wordmodel',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='数据库更新时间'),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='数据库入库时间'),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='translation',
            field=phy_django.models.TextField(blank=True, default=''),
        ),
    ]
