# Generated by Django 4.0.3 on 2022-04-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_alter_wordmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordmodel',
            options={'verbose_name': '单词', 'verbose_name_plural': '单词'},
        ),
    ]
