# Generated by Django 4.0.3 on 2022-04-03 19:35

from django.db import migrations
import phy_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_alter_wordmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordmodel',
            name='stage',
            field=phy_django.models.SmallIntegerField(default=0, verbose_name='学习阶段'),
        ),
    ]
